MS:
-ENH: checking for existence of input

diff --git a/src/scripts/pxmakeCTconemask b/src/scripts/pxmakeCTconemask
--- a/src/scripts/pxmakeCTconemask
+++ b/src/scripts/pxmakeCTconemask
@@ -55,6 +55,12 @@ then
 	exit 1
 fi
 
+if [[ ! -e $in ]]
+then
+	echo "ERROR: The file $in does not exist"
+	exit 1
+fi
+
 if [[ $out == "" ]]
 then
 	base=${in%.*}
